import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://shenailsalon.com";
  const now = new Date();

  // Hub pages
  const hubs: MetadataRoute.Sitemap = [
    { url: base, lastModified: now, changeFrequency: "weekly", priority: 1 },
    { url: `${base}/category/what-are`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/category/how-to`, lastModified: now, changeFrequency: "weekly", priority: 0.9 },
    { url: `${base}/category/california`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
  ];

  // All "What Are" articles (50 total)
  const whatAreArticles: MetadataRoute.Sitemap = [
    "/what-are/what-are-nail-shapes/",
    "/what-are/what-are-nails-made-of/",
    "/what-are/what-are-finger-nails-made-of/",
    "/what-are/what-are-toe-nails-made-of/",
    "/what-are/what-are-dipped-nails/",
    "/what-are/what-are-acrylic-nails/",
    "/what-are/what-are-gel-nails/",
    "/what-are/what-are-dip-nails/",
    "/what-are/what-are-shellac-nails/",
    "/what-are/what-are-gel-x-nails/",
    "/what-are/what-are-press-on-nails/",
    "/what-are/what-are-polygel-nails/",
    "/what-are/what-are-builder-gel-nails/",
    "/what-are/what-are-biab-nails/",
    "/what-are/what-are-solar-nails/",
    "/what-are/what-are-coffin-nails/",
    "/what-are/what-are-chrome-nails/",
    "/what-are/what-are-ombre-nails/",
    "/what-are/what-are-cat-eye-nails/",
    "/what-are/what-are-russian-nails/",
    "/what-are/what-are-paper-nails/",
    "/what-are/what-are-fake-nails/",
    "/what-are/what-are-nail-wraps/",
    "/what-are/what-are-nail-stickers/",
    "/what-are/what-are-nail-tips/",
    "/what-are/what-are-gel-polish-nails/",
    "/what-are/what-are-soak-off-nails/",
    "/what-are/what-are-white-spots-on-nails/",
    "/what-are/what-are-keratin-nails/",
    "/what-are/what-are-abs-plastic-nails/",
    "/what-are/what-are-acrylic-resin-nails/",
    "/what-are/what-are-almond-shaped-nails/",
    "/what-are/what-are-stiletto-nails/",
    "/what-are/what-are-square-nails/",
    "/what-are/what-are-oval-nails/",
    "/what-are/what-are-ballerina-nails/",
    "/what-are/what-are-duck-nails/",
    "/what-are/what-are-flare-nails/",
    "/what-are/what-are-puffin-nails/",
    "/what-are/what-are-glitter-nails/",
    "/what-are/what-are-matte-nails/",
    "/what-are/what-are-marble-nails/",
    "/what-are/what-are-holographic-nails/",
    "/what-are/what-are-3d-nails/",
    "/what-are/what-are-gel-nail-designs/",
    "/what-are/what-are-french-tip-nails/",
    "/what-are/what-are-reverse-french-nails/",
    "/what-are/what-are-half-moon-nails/",
    "/what-are/what-are-negative-space-nails/",
    "/what-are/what-are-nail-extensions/",
    "/what-are/what-are-long-nails/",
  ].map((path) => ({
    url: `${base}${path}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  // All "How To" articles (27 total)
  const howToArticles: MetadataRoute.Sitemap = [
    // Application guides
    "/how-to/how-to-apply-acrylic-nails/",
    "/how-to/how-to-apply-gel-nails/",
    "/how-to/how-to-apply-dip-powder-nails/",
    "/how-to/how-to-apply-press-on-nails/",
    "/how-to/how-to-apply-polygel-nails/",
    "/how-to/how-to-apply-builder-gel/",
    "/how-to/how-to-apply-gel-x-nails/",
    "/how-to/how-to-apply-nail-wraps/",
    "/how-to/how-to-apply-shellac/",
    "/how-to/how-to-apply-paper-nails/",
    // Removal guides
    "/how-to/how-to-remove-acrylic-nails/",
    "/how-to/how-to-remove-gel-nails/",
    "/how-to/how-to-remove-dip-nails/",
    "/how-to/how-to-remove-gel-x-nails/",
    "/how-to/how-to-remove-shellac-nails/",
    "/how-to/how-to-remove-press-on-nails/",
    "/how-to/how-to-remove-glue-on-nails/",
    "/how-to/how-to-remove-fake-nails/",
    "/how-to/how-to-remove-nail-wraps/",
    // Care guides
    "/how-to/how-to-shape-nails/",
    "/how-to/how-to-paint-nails/",
    "/how-to/how-to-strengthen-nails/",
    "/how-to/how-to-make-nails-grow-faster/",
    "/how-to/how-to-stop-biting-nails/",
    "/how-to/how-to-fix-a-broken-nail/",
    "/how-to/how-to-keep-nails-healthy/",
    "/how-to/how-to-file-nails/",
    "/how-to/how-to-push-back-cuticles/",
  ].map((path) => ({
    url: `${base}${path}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  // All California city pages (50 total)
  const californiaPages: MetadataRoute.Sitemap = [
    "/california/nail-salon-los-angeles/",
    "/california/nail-salon-san-francisco/",
    "/california/nail-salon-san-diego/",
    "/california/nail-salon-san-jose/",
    "/california/nail-salon-sacramento/",
    "/california/nail-salon-fresno/",
    "/california/nail-salon-long-beach/",
    "/california/nail-salon-oakland/",
    "/california/nail-salon-anaheim/",
    "/california/nail-salon-santa-ana/",
    "/california/nail-salon-riverside/",
    "/california/nail-salon-stockton/",
    "/california/nail-salon-irvine/",
    "/california/nail-salon-chula-vista/",
    "/california/nail-salon-corona/",
    "/california/nail-salon-santa-clarita/",
    "/california/nail-salon-fontana/",
    "/california/nail-salon-moreno-valley/",
    "/california/nail-salon-rancho-cucamonga/",
    "/california/nail-salon-ontario/",
    "/california/nail-salon-santa-rosa/",
    "/california/nail-salon-bakersfield/",
    "/california/nail-salon-modesto/",
    "/california/nail-salon-fremont/",
    "/california/nail-salon-huntington-beach/",
    "/california/nail-salon-glendale/",
    "/california/nail-salon-palmdale/",
    "/california/nail-salon-salinas/",
    "/california/nail-salon-hayward/",
    "/california/nail-salon-oxnard/",
    "/california/nail-salon-visalia/",
    "/california/nail-salon-simi-valley/",
    "/california/nail-salon-torrance/",
    "/california/nail-salon-sunnyvale/",
    "/california/nail-salon-san-bernardino/",
    "/california/nail-salon-escondido/",
    "/california/nail-salon-orange/",
    "/california/nail-salon-roseville/",
    "/california/nail-salon-fullerton/",
    "/california/nail-salon-santa-clara/",
    "/california/nail-salon-pasadena/",
    "/california/nail-salon-concord/",
    "/california/nail-salon-thousand-oaks/",
    "/california/nail-salon-victorville/",
    "/california/nail-salon-pomona/",
    "/california/nail-salon-lancaster/",
    "/california/nail-salon-garden-grove/",
    "/california/nail-salon-elk-grove/",
    "/california/nail-salon-oceanside/",
    "/california/nail-salon-santa-barbara/",
  ].map((path) => ({
    url: `${base}${path}`,
    lastModified: now,
    changeFrequency: "monthly" as const,
    priority: 0.6,
  }));

  return [...hubs, ...whatAreArticles, ...howToArticles, ...californiaPages];
}
